# Generated by Django 3.2.11 on 2022-02-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to='books/coverimg/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='books/pdfs/'),
        ),
    ]
